label quinn:
    "Over the next few days, Yuki met up with Quinn to go over the assignment."
    "Quinn poured over a giant stack of papers and books. It looked completely disorganized to Yuki, but Quinn seemed to understand where everything was."
    y "So... what are you on now?"
    q "Currently, I'm looking at possible contract templates to discuss with businesses."
    "Considering the only subject Yuki knew was magic, he was stumped."
    y "Well... I'm looking at magic that controls fire."
    q "Oh, that's interesting. Mind if I take a look?"
    "Quinn looked nervous."
    q "I-If that's fine with you."
    y "Of course you can see it."
    "Quinn moved over to sit next to Yuki. The desk was tiny, so their knees touched. Yuki did his best to contain the flush that creeped up his neck."
    q "Huh..."
    "Quinn scrunched her eyebrows."
    q "This is interesting but... It looks quite dangerous."
    y "Everything about magic is dangerous."
    "Yuki tried not to think about a certain type of magic."
    q "Yes, but in the contract rulebook, anything that is this... volatile will take a very long time to approve."
    "Yuki did his best to keep his facial features still."
    y "I see."
    q "Yuki?"
    y "Y-Yes?"
    "Yuki shook his head. This was bad. He was getting too distracted."
    yN "Mother could've really used something like this..."
    yN "Snap out of it."
    q "Yuki?"
    "Quinn looked concerned."
    y "I-It's nothing, haha. Where was I?"
    q "...You've been staring at that page for a very long time."
    y "Yeah... I..."
    "Quinn gently pat Yuki's back."
    q "What's wrong?"
    "Looking into her kind, gentle eyes, Yuki just wanted to spill everything he felt."
    y "..."
    yN "But..."
    "Yuki looked away."
    y "Nothing."
    "Quinn looked at him, annoyed."
    q "Just say it honestly already!"
    "Yuki was shocked. Quinn was never this forward, ever."
    yN "No. This was definitely not the Quinn I knew."
    yN "But I can't risk it."
    y "..."
    "Quinn shook her head."
    q "Come with me. We're taking a break."
    y "Wh—"
    "Quinn grabbed Yuki's hand and led him out the door."
    # hallway
    y "Where are you taking me?"
    q "You'll see."
    "Quinn had a slight smile on her face."
    "Yuki could easily shrug her hand off but he didn't want to. He was partly curious as to what it was as well."
    "Finally, they arrived in a large, green forest."
    y "This is..."
    "A small clay flowerpot with some mud in it lay nearby. Small plants were growing around it, arranged in a haphazard manner."
    y "...your garden?"
    q "That's right."
    "Quinn didn't let go of Yuki's hand. She bent down near the growing plants, signaling Yuki to do the same."
    y "Wow."
    "Yuki bent down to take a closer look. In addition to the flower pot, there were also some miniature gardening tools."
    y "These are cute."
    "Quinn blushed."
    q "T-Thanks."
    "Yuki looked down at the plants. He knew that Quinn loved gardening, but she'd never shown him this place. Was there more she was hiding...?"
    "Quinn waved a hand in front of Yuki."
    q "Are you still here?"
    y "Y-Yeah. Sorry."
    q "I always like coming here and taking care of the plants when I feel down or stressed."
    y "Does that happen often?"
    q "Yes. All our assignments are stressful, difficult, and I constantly wonder... is any of this worth it?"
    "Yuki patted her arm."
    y "Of course it is."
    "Quinn looked at Yuki, her eyes shimmering."
    q "That's what I believe. But it's not easy."
    "Yuki felt a sharp pain in his heart. Trying to think of something else, he points to the plants."
    y "So... if you use magic, these could grow a lot faster."
    q "I know. But the wait is part of the joy in growing plants."
    y "Hm?"
    q "Magic makes men impatient. It makes them want to see the beauty quickly and immediately. They don't want to wait."
    "Quinn took a deep breath."
    q "But look at the plants. They're in no hurry. They have their own time to bloom and fall, and it's a beautiful thing."
    "Yuki stared at Quinn."
    q "S-Sorry, I started speaking and um... I couldn't stop and..."
    q "That's right!"
    "She turned to the flowerpot, and started scraping mud onto it. But Yuki wasn't concentrating on that."
    "He thought about Quinn's words. She was facing her own struggles, her own challenges. But the past him didn't see that. He was too obsessed with himself, his own notions of beauty and romance."
    "Quinn nervously held out the clay pot with a small plant inside."
    q "T-This is for you, i-if you're fine with it!"
    "Quinn's cheeks were dusted with a rosy blush. Yuki glanced between the pot and her."
    "As if overcome by instinct, Yuki leaned his face in closer."
    q "..." # shock
    "Yuki moved in closer, giving her time to react. But Quinn just closed her eyes."
    # CG
    "Yuki kissed her on the lips."
    "It felt like everything clicked in place. Yuki felt a feeling of calm wash over him. Quinn slowly began to kiss him back."
    q "Mm..."
    "Yuki loved the feeling of his lips on hers. He slowly deepened the kiss, and Quinn responded in turn."
    yN "This is... amazing."
    "Quinn tilted her head to the side. Yuki licked her bottom lip and she gasped."
    "Yuki nuzzled his nose with hers, taking a breather for air."
    y "You're wonderful."
    q "...!"
    "Without giving her a chance to respond, Yuki kissed her once again."
    "Finally, Yuki broke the kiss."
    y "{i}pant{/i}"
    q "{i}pant{/i}"
    y "So..."
    q "U-Um... t-that was... w-well..."
    "Yuki smiled at her nervous words."
    y "I care about you, Quinn. I love how kind you are to others and how you smile when looking at the plants. I truly love the way your face lights up when you talk about something you love."
    y "I-If you want this... I would love to be with you. As your partner."
    q "I-I... U-Um..."
    "Quinn's eyes darted from side to side, and Yuki was afraid he'd made a terrible mistake."
    y "S-Sorry if that made you uncomfortable..."
    q "No! No, that's not it at all. I'm happy. Very happy."
    y "Really?"
    q "Yes. I-I'm not too knowledgable about this but... I'd love to be yours as well."
    "Yuki pulled Quinn into a tight hug."
    y "I promise, I'll make you the happiest woman in the world."
    q "I-it's okay. Because you already have."
    call research 
    call .fun
    call finalMother

label .fun:
    "Over the next few weeks, Yuki and Quinn went to several different places on dates. They took turns picking out locations."
    "Yuki and Quinn returned back to her dorm after a trip to an exotic garden."
    y "Haah..."
    "Yuki flopped down onto Quinn's bed, and she followed suit."
    y "That was beautiful but... so much walking."
    "Quinn laughed softly."
    q "Yes. Thank you for coming with me."
    "Yuki turned to face Quinn and gave her a light peck on the lips."
    y "Anything for you."
    "Quinn snuggled into Yuki's arms and hugged him."
    q "You're so sweet."
    y "I know."
    "Quinn laughed and touched her finger to Yuki's nose."
    "Yuki smiled down at her."
    yN "I'll protect this smile forever."
    yN "Everything will work out."

    return 

label .ending:
    "Quinn stood in the doorway, her face flushed with exertion."
    q "STOP! STOP THIS RIGHT NOW!"
    "Yuki looked at her, shocked."
    y "How do you..."
    "He shook his head."
    y "Doesn't matter. Stay out of this, Quinn."
    q "NO! I saw your books. You can't do this Yuki, you'll DIE!"
    "Yuki turned to her, rage flooding his being. It was just like before, she thought he was too stupid and cowardly to pull it off."
    y "Then run! Get away from me!"
    q "NO!"
    "Yuki felt agitated. This was supposed to be the final spell, the one that would save his mother."
    "He glanced at Quinn. She stood at the edge of the room. If he cast the spell now, it would be done before she could do anything about it."
    "Yuki decided..."

    menu:
        "To cast the spell":
            call .bad
        "Not to cast the spell":
            call .good
    
    return

label .bad:
    "Yuki steeled his nerves. This was why he came back, after all."
    "He took in a deep breath and began chanting."
    y "w̸̧͖̩͕̰̋̈̂̈́́͗̽̇͝͝a̸̤̮̹̳̭͖͂̐̋̿̑̅̆̒͌͊̚͠͠ẹ̴̛͐́̑̈́̐̅̿͠ȑ̵̨͚͈͙̻͍̘̪̭̟̩̦̟̓̄͒͛̌͗̑̔f̴̡̟̪͎̦̣͔̖̫̯͈́͆́́̈́̈́̋̏͐́̓̐͛̉ǧ̷̜̬̽̒̎͗̃͑̋̿́̅͆͝d̷͙̹͈͈͚̣̳̰̒̍͂̉͒͑͋͑̈́̋͝ͅt̷̡̟̯̜̹̲̜͙̦̽̄̍̀͠f̷̧̨͕̤͒̀h̷̝̖͙͕͔̰̣͓̿̅̀̓̃̄͘͜͝͝ỳ̶͚̬͙̹̏̄̇͋̃̽̔̏͝͝͝ͅġ̶̥͖͖̻̞͖͇̹̹̍̇j̶͎̼̹̜͕̟̭̼̦͊̓̽̿̔̒̔̀k̵̨̳̘̠̥̳͚͌́̒̆͜͝ḣ̷̨̖͔̣́̅̒̿̍̔͋̂̀̽̈̒͘ͅg̸̙̜̟̼̺͍̫̦͗̐f̶̣̰̖͈̔̎̐d̶̤̱̯̮͇̦̜̾̆̉̈́͌̀͛͋͘͝s̷̨̨̖̫̀̐̐̆̒͆̄a̶̲̞̖͓̬͈͈̻̔͒͊̾͌̕͜s̴̡̜̫̼̼̔͑c̷̨͕̙̺̻̜̲̦̠̥͖͎͋͠d̸̛̤̬̹̭͙͂̀͑͐̒̑̽͛́̿͗̄̊͘v̶̢̛͉̠̳͚̘̀̈̊̈́̂̽̌́̈́̓̑̊͘̚b̵̡̧̛͚̰̗̘̼͔͇̜̦̮̉͒̾̔̽̀͘͠͝ͅṅ̶̥̯͉̥̪̜̓̈̄̎͒̅̀͋̈́͝ͅ ̶̨̡̙̘̤̭̖̥̻̥̖̗̈́͆͊̈́̎͐̅̈̄͘͘͠"
    
    
    q "NO! YUKI!!"
    "Her voice felt distant. Like it was underwater."
    "Yuki's body began to burn with pain."
    y "AHHHHHHHHHHHHHHHHHHHHH!!!!!!!!!!"
    "Yuki screamed in agony. It felt like his body was being ripped from the inside out while being immersed in lava."
    y "I can't...It hurts...!"
    "Yuki continued to scream and shout."
    q "Yuki...! Yuki!!"
    "Quinn's voice sounded strange. The pitch fluctuated, and it was hollow."
    "With incredible effort, Yuki lifted his eyes. He could make out nothing more than a blur."
    #quinn Crying CG
    "His eyesight came back with clarity, but his body ached."
    y "Is it... is it over?"
    "Quinn stood over him, her tears falling on his face."
    "Yuki tried to lift his arm to wipe them away, but he couldn't move."
    q "I love you! I love you more than anything else in this world, Yuki! Don't leave me!"
    "Yuki wanted to reply, to say that it was all okay. But his mouth didn't move. His voice didn't come out."
    yN "What's... what's happening?"
    q "Stay with me, okay? Please! Yuki! I-I'll do anything... please! Don't go!"
    "Quinn tried to shake me, but it felt like a tap on the shoulder."
    yN yN "I want to say... I love you too."
    "Still, no words came out of his mouth."
    q "No... not like this! Please!"
    "The world plunged into darkness."

    # Epilogue
    "Five years later..."
    "Quinn put on her best smile."
    q "Mrs. Zen'Ichirou?"
    "No response."
    "Quinn's smile wavered."
    "Silently, Quinn opened the door of the cabin and entered."
    "Yuki's mother sat in a chair, staring into the distance, unmoving."
    "Although the spell Yuki performed did work, it left Yuki's mother mentally broken. She couldn't accept the fact her son was dead, and spent her days staring into the distance."
    "Silently, Quinn left food supplies at the door and left."
    "She felt she didn't have the right to talk to her. Quinn should've known what Yuki was going to do. She should've stopped him earlier."
    "She wiped the edges of her eyes."
    q "{i}(No. You have to be strong, Quinn.){/i}"
    "After Yuki died, she dropped out of college and begun a pharmaceutical company. Her parents were furious, but she didn't care."
    q "They found a cure for the disease Yuki's mother suffered from years later. But it was too late."
    "As Quinn made her way through the woods, she saw an injured cat lying outside."
    q "Oh no... you poor thing!"
    "She picked the cat up and cradled it in her arms."
    cat "..."
    q "Come. I will treat you at home."

label .good:
    "Yuki looked at Quinn."
    "He sighed and dropped his arms."
    y "...Very well."
    "Quinn ran into the room and hugged Yuki tightly."
    q "Oh, thank the heavens... Yuki...!"
    "Yuki felt tears prick the edges of his vision. He hugged her back tightly."
    y "Quinn... I..."
    q "It's okay. It's okay, love. I'm here for you."
    "Yuki buried his face in Quinn's hair."
    y "I... I just wanted her to live!"
    q "I know, I know."
    "Quinn rubbed his back comfortingly."
    q "Yuki..."
    y "I {i}know{/i} that death is a part of life. I know that she is going to a better place."
    y "I just... I just...!"
    "Quinn turned her head up and looked at him."
    "She wiped the tears from his eyes."
    q "I understand, Yuki. You're so strong for doing this."
    "Yuki cried harder. Despite being surrounded by various dead animals, he felt a strange relief wash over him."
    q "It's okay now. It's okay."
    "Quinn's comforting voice was medicine to Yuki's ears. He felt calmer. His heartbeat steadied, and his hands stopped shaking."
    q "Let's go back now, okay?"
    "Quinn's voice was soft."
    y "...Yes."
    "However, Yuki's body was physically drained. Despite struggling, Quinn supported Yuki on her shoulder all the way back."

    "Five years later..."
    "Yuki stood in his cabin, humming. He set a pot full of water on the stove and watched it boil."
    # quinn appears
    q "..."
    y "Quinn!"
    "Yuki rushed over to Quinn and hugged her."
    y "You're early today. How was work?"
    "She sighed tiredly."
    q "It was exhausting."
    y "I thought so, that's why I was getting your favorite soup ready but..."
    "Yuki scratched the back of his neck sheepishly."
    y "You came early."
    "Quinn giggled. It sounded exactly the same as it did half a decade ago, and Yuki loved the sound."
    q "That's fine! I can help you with it."
    y "But I wanted to do it!"
    q "You're probably just going to burn it again."
    y "The seventh time's the charm, right?"
    q "...If you insist."
    "Quinn sat down in a corner of the room and watched Yuki put everything together."
    y "How are the negotiations going?"
    "Quinn sighed."
    q "The leaders are really stubborn... They don't want to approve the treatment program."
    "Yuki gripped the ladle tighter."
    q "Yuki..."
    q "It's—It's okay. I can handle it."
    "Yuki's mother was proclaimed dead just a fews hours after the incident on that fateful day. Although Yuki couldn't make the funeral, he visited her grave immediately after the semester ended."
    "Since the successful completion of their project, Yuki became very interested in research to cure diseases. After graduating, Quinn started a medical research facility, of which Yuki was one of the first employees."
    "They worked tirelessly night and day to create a way to detect and cure the illness Yuki's mother had all those years ago."
    "Yet..."
    "Yuki wordlessly stirred the soup."
    q "..."
    "Quinn stood behind Yuki and wrapped his arms around his waist."
    y "Quinn..."
    q "Shh... It's okay."
    "Yuki took solace in the comfortable silence. Finally, the lumps in the soup began to dissolve."
    y "Great! It's almost done."
    q "I'm glad."
    "Despite the city being a more convenient place to stay, Quinn and Yuki set up home in a cabin in the woods."
    "They enjoyed going for long, picturesque walks, and could teleport to work easily since they set up a special rune."
    "Quinn and Yuki sat down and drank the soup quickly."
    q "Hah... Work really is hard, isn't it?"
    y "..."
    q "Is there something wrong?"
    y "H-Huh? Oh, nothing. Say, do you want to take a walk?"
    "Quinn's face lit up."
    q "Of course!"
    "Yuki nervously led Quinn to their usual spot for a walk. He did his best to keep up with the conversation but his mind kept drifting elsewhere."
    q "Yuki? Are you alright?"
    y "Y-Yeah."
    q "You don't seem to be..."
    "She raised her hand and touched Yuki's forehead."
    q "Hm... seems fine."
    y "I just... I wasn't sure how to tell you this."
    "Yuki got down on one knee and pulled out a ring."
    q "T-This is..."
    y "I want you to marry me."
    "Quinn had tears in her eyes."
    q "Of course! I will. Yuki, oh, you didn't have to—"
    "Yuki slipped the finger onto Quinn's hand and kissed her."
    "They knew that this wasn't the end. Everything wasn't perfect, but they knew one thing."
    "This wasn't the end."
    cat "...Interesting. Humans are quite peculiar." 
    # END
