label cafeteria:
    "The next few weeks passed by quite uneventfully."
    "Yuki easily breezed through all his classes, with nothing interesting of note happening."
    cat "..."
    y "Don't look at me like that!"
    cat "Is this why I gave you a second life?"
    y "I don't know! I didn't even ask for this!"
    cat "But it's what you wanted."
    y "I-I..."
    "Yuki couldn't deny her words. It was true, this was what he wanted."
    cat "Don't waste it. You won't get another."
    y "..."
    "Yuki spend the past few weeks doing his very best to avoid both Zethe and Quinn. He felt a gutteral response whenever he was around them."
    "Sighing, he walked to the bookshelf in the corner of his room and pulled out his book of Vednore perks."
    "He flipped through the pages."
    yN "The one I'm looking for is—"
    y "Ow!"
    "Yuki flinched and dropped the book on the ground."
    "He clenched his hand in pain."
    y "Crap, crap, crap!"
    "Instinctively, he brought up his other hand and began to cast a basic cooling spell. Instead, icicles formed outside his window."
    y "Dammit!"
    "He cursed and sat down on his bed, waiting for the pain to subside."
    y "Phew..."
    "He took a deep breath."
    "Ever since he fell on his first day of classes, Yuki's wrist was hurting. Probably since he fell right on it."
    y "Ugh..."
    "After a couple moments rest, he walked over to where he'd dropped the book and picked it up."
    y "As I was looking..."
    "Yuki flipped over to the page that read, 'Food Delivery Tickets.' He knew he was running low but..."
    y "Goshdarnit."
    "He was out of tickets. He'd used them all the past weeks."
    "That meant he actually had to go to the cafeteria. Like in person. And interact with other humans."
    cat "Well, well, well."
    y "You sure are enjoying this."
    cat "Of course I am. Have fun!"
    "Yuki grumbled and made his way to the cafeteria."

    #cafeteria BG
    "Yuki got his food on a tray. He precariously held it so as not to aggrevate his already painful wrist."
    "Looking around, all the seats were taken. Except ones next to Zethe and Quinn."
    yN "That's what I get for showing up so late..."
    "Torn, he finally decided to sit next to..."

    menu:
        "Zethe":
            "Zethe was sitting next to a group of other nobility."
            "Yuki felt a little intimidated, but wasn't about to be swayed."
            "However, it appeared that the nobles were mostly conversing amongst themselves, with Zethe quietly picking at his food."
            "Yuki sat down next to Zethe. Internally, he felt shaken. But he didn't show it."
            z "Oh? Look who's here."
            "The other noble students gave a cursory glance at Yuki before returning to their conversations."
            y "I have a name."
            z "Yuki, I know."
            y "Wow, I'm so honored."
            z "You should be."
            "Yuki ignored Zethe and took a spoonful of soup. He hoped that it would be easy enough to eat."
            "Unfortunately, his hand shook with discomfort. Still, he raised it into his mouth and drank it."
            z "..."
            y "...What are you looking at?"
            "Yuki braced himself for a snarky retort."
            z "Give me your hand."
            y "What?"
            "Without another word, Zethe grabbed Yuki's hand."
            y "W-What are you doing?!"
            "Zethe began chanting silently. Yuki felt a cooling sensation on his hand as the pain began to fade away."
            y "Wow."
            "Yuki flexed his fingers and rotated his wrist. It felt completely normal."
            y "Not bad."
            "Zethe clicked his tongue."
            z "I help you out, and I get a {i}not bad?{/i}"
            y "That's right. I feel a little tingle, so it's not considered {i}good{/i}."
            z "Hmph. You should be grateful: the only reason I helped you is because it's no fun fighting against an injured rival."
            "Yuki chuckled and went back to drinking his soup. He could've healed the injury himself much earlier, but he was conserving his magic in case of future incidents. But Zethe clearly didn't have any such reservations."
            y "I doubt you'd stand a chance against me at full strength."
            "Zethe smirked."
            z "Oh? You should worry about yourself first. Fainting on the first day of class is never a good look."
            "We bickered over lunch. Surprisingly, Zethe wasn't as bad as I'd originally thought."

            
        "Quinn":
            "Quinn was sitting at a table by herself. However, there was one empty chair next to her."
            "Instinctively, Yuki straightened out his collar and brushed his hair."
            yN "Crap. What am I doing?"
            "Yuki shook his head to clear his thoughts. Then, he walked up to her table and sat down."
            q "O-Oh! Hello, Yuki."
            y "Hey Quinn. This is the only spot I found. Hope you don't mind."
            "Yuki did his best to keep the ice out of his voice. He felt strange: fluctuating between gentle desire to stay by her side, and harsh memories of his hurt in the past."
            q "Of course not!"
            y "That's good."
            "Yuki lifted a spoonful of soup to his mouth. He'd hoped it would be easy enough to eat."
            "However, his hand began to shake with discomfort."
            y "Hngh."
            "With difficulty, Yuki brought the spoon to his mouth and swallowed."
            q "..."
            q "That looks difficult."
            y "Haha, yeah. Don't worry about it, I'm fine."
            "Yuki took another spoonful, but a sharp pang of pain made him drop it into the bowl."
            y "Ow!"
            q "Yuki..."
            y "I'm fine, I'm fine."
            "He didn't want Quinn to worry about him. He closed his eyes for a second and opened them."
            y "...?"
            "The bowl was sitting by Quinn's side now. She held the spoon in her hands."
            q "Say 'Ahh.'"
            y "H-Huh?!"
            "A light blush dusted Quinn's cheeks, but she persisted."
            q "If you can't eat, I'll help you out."
            y "I-I appreciate it, but..."
            q "It's okay, you don't need to act tough."
            "Meekly, I gave in."
            y "Ahh."
            "She smiled and helped Yuki to a spoonful of soup."
            y "Thanks."
            q "It's okay. Injured people shouldn't have to do work."
            "Yuki doubted eating was considered work, but he didn't complain."
            "They ate the rest of their meal in silence. Quinn was just as he'd remembered: beautiful both inside and out."
        
    "But memories of his past life clutched his chest. He couldn't let go of them so easy."

    return

label library:
    "A few more weeks passed."
    "The classes began to get a lot tougher. Considering he'd been out of college for a while, Yuki struggled to remember everything. So, he found himself spending more and more time at the library."
    "But he was there today for a very different reason."
    y "..."
    "Yuki furrowed his brow in concentration as he read, 'Lola: My First Guardian Spirit.' to himself."
    cat "Are you kidding me?"
    yN "Shh! I'm doing research."
    "Yuki read the contents of the book to himself. It was a book about a Guardian Spirit who helps out a crying child in his quest for greatness."
    "Aurelia looked suspiciously at the book in Yuki's hands. It was comprised mostly of colorful images and baby speech."
    cat "This is why I didn't want to bother with mortals."
    z "It appears that our class prodigy has taken to reading children's books in his spare time."
    "Yuki ignored the voice and continued reading."
    z "I said—"
    y "Hm... I think I hear some wind rustling in the distance."
    "Yuki peeked from the corner of his book to see Zethe visibly annoyed."
    z "Tch!"
    "Zethe stormed off. Yuki just shook his head. He was in the middle of something important."
    yN "Oh! So this Guardian Spirit took him on an adventure to a land of candy, where everything is made of fluffy sweets!"
    cat "..."
    "After he finished the book, Yuki put it down and picked up another. All of them had widely differing plots, but Yuki was noting down the similarities and differences between them in a notebook."
    "Yuki was almost finished when he looked outside."
    yN "It's extremely late."
    "Just as he was getting ready to leave, another familiar face appeared next to him."
    y "Quinn?"
    q "Yuki! What a surprise. Oh, is that the 'Guardian Spirit of Love' series I see?"
    "Yuki blushed as he realized he had a stack of children's books next to him. But Quinn looked delighted."
    q "That was my favorite series growing up!"
    y "Really? I hadn't got the chance to read that series yet, though I've been looking at others. Mind telling me more about it?"
    q "Sure! So there's this really mischevious spirit named Lola..."
    "After hearing Quinn's fantastical tale of the Guardian Spirits in the series, Yuki was convinced it had nothing to do with reality in any way."
    q "...And then, Lola does a backflip into the chocolate fountain!"
    y "I think I get it."
    q "O-Oh. Sorry, I rambled for a bit."
    y "It's fine. It's cute when you do that."
    "The words slipped out of his mouth unwittingly, and Yuki regretted them instantly."
    y "I-I didn't mean it like—"
    q "It's... it's fine."
    "Quinn was blushing furiously."
    q "I-I have to go."
    "For a moment, Yuki thought about stopping her. That's what he would've done in the past. Stop her, convince her to give him another chance. But now..."
    yN "I should let her think."
    "He began to walk out when he felt a hand on his shoulder. Yuki flinched."
    y "H-Huh?!"
    "Yuki turned around to see Zethe glaring at him. Yuki breathed a sigh of relief."
    y "Oh. It's you."
    z "Do not give me that."
    y "What?"
    z "{i}Oh, it's you{/i}"
    y "Listen Zethe, I really don't have time for this—"
    z "Sure, but you were just talking to Quinn for a while now."
    "Yuki sighed. He knew Zethe was crushing on Quinn, so this would be troublesome."
    z "Why did you talk to her, but not to me?"
    yN "Huh?"
    z "When I attempted to converse with you, you brushed me off. You refused to even look at me. But you had a full conversation with Quinn."
    "It was strange that Zethe was watching their whole conversation, but also the way he was talking... It was almost as if Zethe was jealous of Quinn, not Yuki."
    "Zethe shook his head."
    z "I suppose you will not talk to me now, either. Very well."
    "He turned on his heel and walked out the door."
    "Yuki's mouth hung open in shock. What a surprising day."
    yN "I should go home and sleep on it."
    "Aurelia sat in the corner, her tail wagging in interest."

    return

label mother_call:
    "A few more days passed. Yuki sat in his room working on a particularly difficult assignment. Aurelia was in the corner, curled up and snoring loudly."
    "But Yuki couldn't concentrate. His hands shook as he tried to read the words on his notebook."
    "Yuki knew from the calendar that it was the day he dreaded."
    "After a few more hours of thoroughly unproductive work, Yuki sat the pen down on the desk."
    y "Hah..."
    "Yuki's messenger note, the one on the wall, began to flash brightly. He flinched, but collected himself enough to answer."
    "A holographic projection of Yuki's mother shone in front of him."
    y "Mother."
    mom "Hello, my boy. How are you doing?"
    "Yuki stared at her. Her arms were weak and frail. She looked feeble."
    y "I'm... I'm alright. What about you?"
    mom "Dear, I'm afraid to say... I don't have much time left."
    "Yuki had heard this declaration before. But it still felt like he got the wind knocked out of him. Yuki clutched his stomach."
    y "Mother..."
    mom "Don't look so upset, dear."
    "He knew his mother would protest to his next words, but Yuki said them anyway."
    y "I will come to see you at once."
    "His mother's voice turned angry."
    mom "No! Do you not realize how far I am? It would take you at least three months by sea."
    y "I won't use sea. I'll teleport. I must see you."
    mom "Yuki... It's not worth it. There are no teleportation runes anywhere near here, so you'd still have to—"
    y "I KNOW!"
    "Yuki felt guilty for raising his voice. Tears pricked at his eyes."
    y "I... I know, mother. There's no point. There's nothing that can be done."
    mom "My boy..."
    "Yuki felt his chest heave. His mother rarely called him by name. It was always 'My boy.' But now, he'd never be able to hear that sweet voice of hers again."
    "Yuki knew that it was just a projection, but he reached his hands out to it."
    y "Mother, I love you."
    mom "I love you too, my boy."
    y "I can't let you go like this."
    mom "Death is not something to be feared. It should be celebrated."
    y "But..."
    mom "Yuki. I'm so proud of you. You managed to get a scholarship to such a prestigious school."
    y "I promised. I promised I would bring you out of that awful, violence-ridden place."
    "Mother's look turned stern."
    mom "It is not perfect, but {i}that place{/i} is still your home."
    "Yuki knew there was no point in arguing with her. She was as stubborn, if not more than Yuki himself. He decided to drop it. He didn't want to spend their last real conversation arguing."
    yN "Last time, we parted too bitterly..."
    "After some more conversation about various happenings in town, Mother's eyes began to droop. The connection became fuzzy."
    mom "Oh, our time's up. Remember this, my boy. Some things happen for a reason. And I love you. Now and always."
    y "I love you too, Mother."
    "And with that, the line cut. Yuki felt his eyes water."
    "Yuki walked over to the bookshelf next to him and pulled out Mother's amulet. He clenched it in his fist."
    yN "Perhaps I can still keep that promise."
    "Deep down, Yuki felt he should..."

    menu:
        "Accept the death as inevitable":
            "Maybe it was like what Mother said."
            "Death was a vital part of the cycle of life."
            "But even if it was inevitable, it could be delayed. That was the premise of many medicines, after all."
            "Even though he felt it wrong, nothing could stop the fire inside..."

        "Change fate":
            yN "Isn't this why I got a second chance? To defy fate?"
            "And if fate thought she could rip his dear Mother away, she had another thing coming..."
            yN "'Death shouldn't be feared.' As if I'm scared of it!"
            yN "Do your worst, fate. I won't be defeated."

    return

label assignment:
    "Yuki sat in the classroom, nervous. It was the final class of the day."
    "He tapped his finger on the desk. The past few weeks, he'd been researching various healing techniques."
    "None of them said anything about terminal illnesses. He knew that from his previous life at Vednore, so he was researching different books this time. Still, they turned up nothing."
    prof "For the final grade of the year, you will have to partner with another classmate for a special assignment."
    "The year had passed by in the blink of an eye. He clutched Mother's amulet. As long as it glowed, it was proof she was alive. But the light was dimming. There wasn't much time."
    "Normally Yuki found Professor Chen's lectures interesting. Now he just wanted it to be done with."
    prof "You have two options. You can partner up with another magician to create a new spell."
    "The class went crazy with whispers. All spells that students performed were taken from old books. Sometimes, they were tweaked to fit modern needs. But no one {i}ever{/i} created their own."
    "Professor Chen cleared his throat."
    prof "But I realize that is a monumental feat, not one that many desire. As a result, there is a second option."
    prof "You may partner with a student from the {i}Juris{/i} program to make a magical product."
    "A magical product required not just the magic component, but a detailed legal contract to ensure no issues arose. In his previous life, Yuki partnered with Quinn to make the eternal garden in the center of the school. It wasn't really a product that could be sold on a shelf, but they got a perfect grade anyway."
    "This time, Yuki felt more conflicted. Quinn's attitude was very different. Since he didn't push her, she was much more spontaneous and excited, which made him feel that they may have a real chance together..."
    "On the other hand, Zethe's curious behavior drew Yuki's eye as well. Before, he just considered Zethe a worthy rival. But now, he felt something else..."

    "What should Yuki do?"

    menu:
        "Make a magical product with Quinn":
            "It was a different timeline, but Yuki still deeply cared about Quinn. Maybe even deeper now that he knew her true nature."
            "After class, Yuki waited in the hallway for Quinn to come out."
            q "Yuki?"
            y "Hi Quinn. I just wanted to ask you something."
            "Her cheeks flushed red."
            q "L-Like?"
            y "O-Oh, don't worry. It's nothing personal."
            "For a second, Quinn looked disappointed. But she quickly recovered."
            q "Oh. Well. Go ahead!"
            "Her reaction was strange, but Yuki didn't think too much of it."
            y "I wanted to know if you were willing to partner with me for the final assignment?"
            "Quinn looked surprised."
            q "You want to partner with {i}me?{/i}"
            y "Is... Is there a problem?"
            q "No, uh, I thought you had an issue with me."
            "Yuki blinked."
            y "What made you think that?"
            q "I-It's nothing. It was just a misunderstanding, that's all."
            "Yuki chewed the inside of his lip. In his previous life, they did the flashy garden display. But Yuki basically did the entire thing by himself, with Quinn barely giving any input."
            "Yuki felt guilty."
            y "So... what do you want to do?"
            "Quinn's eyes lit up."
            q "I want to make a small stove for ill and disabled people. Something that will let them cook simple meals without difficulty."
            "Yuki was surprised."
            y "I didn't know you were interested in that."
            "Quinn pouted."
            q "You never asked."
            "Yuki thought for a moment. She was right: he knew she loved plants and flowers, but that was it."
            y "Sounds good. Let's discuss the details later?"
            q "Sure! We can meet at my dorm."
            "After exchanging Holo Note information and discussing timings, Yuki made his way back to his dorms."
            z "..."
            y "Zethe."
            z "Yuki."
            "Yuki crossed his arms and waited for Zethe to speak."
            z "About the final grade of the year."
            y "Yes?"
            z "Do you have a partner yet?"
            "Yuki studied Zethe's features. He looked strangely nervous."
            y "Yes, I'm partnered with Quinn."
            "Zethe's face instantly fell."
            "Yuki remembered he had a massive crush on Quinn."
            yN "Must suck."
            "He pat Zethe's shoulder and walked past him wordlessly."
            call quinn

        "Create a new spell with Zethe":
            "Yuki knew he was up for a new challenge. And he knew just the person to take it on with."
            "After class, Yuki stood outside the door. He watched various students shuffle out and discuss different ideas."
            "Finally, he spotted Zethe."
            y "Zethe."
            z "Yuki."
            y "I have something to ask you."
            "Zethe's eyes grew wide as saucers."
            z "Huh?"
            "Yuki was surprised by Zethe's reaction."
            y "It's... not about a duel."
            z "Okay..."
            "Zethe's expression still didn't change."
            y "...It's nothing personal, either."
            "Zethe's face immediately fell, but he straighted himself."
            z "Is that so? Can't you explain it in a proper manner?"
            "Yuki shook his head."
            y "Do you want to create a new spell together?"
            "Zethe's jaw dropped in visible shock."
            z "Do you even know what you propose?"
            y "Yes. Unless... you don't think you can do it?"
            "Predictably, Zethe took the bait."
            z "Of {i}course{/i} I can. You're the one who'd struggle to keep up."
            "Yuki brought his hand to his mouth in a fake yawn."
            "Zethe scoffed."
            "Yuki felt a smile stretch across his face. Something about Zethe brought out his inner child. Competitive yet immature."
            z "What are you laughing at?"
            y "At your inevitable defeat."
            "Zethe took a moment to think."
            z "No one can lose in a group project."
            y "I suppose I would, when you invetably fall behind."
            z "You...!"
            "After some more childish bickering, Yuki realized they were getting no where."
            y "What should the spell do?"
            z "Good question."
            y "..."
            z "..."
            y "..."
            z "How about... a massive phoneix."
            y "That does... what exactly?"
            z "It will be a large bird. Made of fire. That flies."
            y "Zethe, I know what a phoneix {i}is.{/i}"
            z "Great. So there's no problems there."
            "Yuki rubbed a hand on his forehead. What had he signed up for...?"
            y "Alright. Give me your information so we can figure out something actually do-able."
            "Zethe protested, but eventually exchanged Holo Note information and discussed timings."
            y "We can meet at my dorm room."
            z "That works."
            "After splitting ways with Zethe, Yuki sees Quinn in the hallway."
            q "Yuki?"
            y "Oh hello, Quinn."
            q "Hi. I was um... just wondering if you hand a partner for the final projecT?"
            "Yuki blinked."
            y "Yeah, I do. I'm partnering up with Zethe."
            q "Oh! Oh. Okay then. Just... I was just checking."
            "Yuki could've sworn he saw sadness reflected in her eyes. Before he could say anything, she quickly scurried away."
            yN "Did she... did she want to partner with me for it?"
            "Yuki shook his head. That wasn't possible. Quinn wasn't ever so forward."
            call zethe

    return

label research:
    "Yuki sneaked into the library at night."
    "Although the library had several magic protection locks, Yuki got through because..."
    
    if passed:
        "After passing the first exam, Professor Chen trusted Yuki a lot more."
        "Naturally, Yuki eventually found himself entrusted with the keys."

    else:
        "He failed the first exam, but worked on his raw magical skill a lot more."
        "He easily passed through the complex web of security with finesse."
    
    yN "So naive..."
    "He went straight to the back of the library and chanted a spell."

    #bg: Yukis lab.

    "Yuki felt at ease in his lab. He went around to the spell books and flipped through them."
    "The spells here were far more difficult, complex, and dangerous than any he'd done before."
    yN "As if that would stop me."
    "The final one was in a language he couldn't understand. The glyphs followed no rhyme or reason."
    "After intense study, he realized that it was because they changed everytime he opened it."
    yN "Now...!"
    "He closed his eyes and funneled silent magic through it until it shattered."

    #boom sfx
    y "What the?!"
    "Yuki opened his eyes."
    "The only remains of the book was writing etched on the ground."
    "It was in..."
    yN "Blood?!"
    "It read, 'In order to save a life, something of equal value must be sacrified. Be prepared.'"
    "Yuki slammed his fist on the table."
    yN "This isn't helpful!"
    "He stared down at the fading amulet."
    yN "I failed last time. It won't happen again."



