label zethe:
    "Over the next few days, Yuki and Zethe met up in Yuki's dorm to discuss the project."
    z "No matter how many times I visit, I find this place too narrow."
    "Yuki rolled his eyes."
    y "Okay, Mr. Rich Guy."
    "Zethe grumbled and settled in the chair next to Yuki."
    "Yuki adjusted his tie. Two guys in such tiny dorm got hot very quickly."
    z "Since we are creating a phoenix, we will require—"
    y "We're not making a phoenix."
    z "Why not?!"
    "Yuki rested his head in his hands."
    y "Are we going to go over this again..."
    z "It's not like you're any better."
    y "You don't understand. A spell that dispenses healing magic over a wide range is far superior!"
    z "There's already a spell for that!"
    y "But it would be in the shape of a teddy bear!"
    z "That's commpletely useless!"
    "After they argued some more, they finally decided on a compromise: A phoenix that healed over a wide range."
    z "The amount of components we would have to keep in mind..."
    y "That's why we're on it together."
    "Zethe went uncharacteristically quiet."
    "Since they'd finally agreed on a subject, Yuki smiled."
    yN "This might actually work out..."

    call research

    "Yuki and Zethe sat down together and researched magic techniques."
    "Yuki went through many different spell books at a rapid pace."
    z "How do you read so fast?"
    "Zethe looked genuinely puzzled."
    y "Practice."
    "Yuki couldn't tell him he had another decade of doing nothing but reading books in an empty cabin."
    "Despite his best efforts to cover it up, Zethe had difficulty reading for long periods of time."
    y "Zethe."
    z "Hmm?"
    y "How about this: I read theoretical techniques for now, while you finish sketching possible summoning circles."
    "Zethe sighed in relief."
    z "Alright."
    "Zethe pulled out a paper and began to draw several intricate patterns in a flash. Something Yuki could never do."
    "Sighing, Yuki went back to his reasearch. A heading in the book caught his eye."
    yN "Magic from heartbreak."
    "Yuki glanced over at Zethe who was engrossed in his work. He felt his heart skip a bit."
    yN "Am I... feeling something for him?"
    "From the beginning, Yuki tried to deny his feelings for Zethe. He tried to push it down."
    "But now... now it was something he couldn't deny anymore."
    "Looking over at his chiseled face, his beautiful eyes..."
    "Then it struck Yuki. Zethe didn't care for him. He was in love with Quinn. Just as he himself was in his previous life."
    "Yuki frowned. It was too much. He got up suddenly, startling Zethe."
    y "I-I'll be going for a bit."
    z "What?"
    "Zethe grabbed Yuki's arm. His eyes flit over to the passage Yuki just read and his cheeks heated."
    y "..."
    yN "This is mortifying!"
    "He yanked his arm away."
    y "S-Sorry. I'll be going for a bit."
    return

label .kiss:
    "But then, Zethe grabbed Yuki's arm and pulled [him] closer."
    z "Yuki! Listen to me."
    "Yuki felt a pain in [his] heart. [He] knew that Zethe didn't love [him]... he was in love with Quinn. That was how it was."
    "But when Zethe looked at [him] with such fire in his eyes, Yuki couldn't look away."
    y "What is it?"
    "Yuki steeled [his] nerves and looked at Zethe right in the eyes."
    z "I..."
    "For a brief moment, Zethe's gaze dropped to Yuki's lips."
    y "What?"
    z "I..."
    "Zethe raised his fingers to Yuki's face and caressed it gently."
    yN "(H-Huh?!)"
    "Zethe's gentle touch turned into a tight grasp as he pulled Yuki's face even closer."
    z "You're just so...."
    "And kissed [him]."
    "Yuki's mind went blank as Zethe's lips touched [his]. They were soft and warm, with a hint of spice on top."
    y "Mmph...!"
    "Without realizing it, Yuki slid [his] arms around Zethe's waist and pulled them closer. Yuki felt Zethe's muscles flex under [his] touch,
    and felt a rush of pleasure go straight to [his] head."
    z "Mm..."
    "Zethe tilted his head to deepen the kiss, and Yuki returned the gesture."
    "Yuki began to feel lightheaded and breathless. It felt amazing, yet—"
    "Suddenly, Zethe pushed Yuki's shoulders away, breaking the kiss. Yuki licked [his] lips, missing the feeling already. Zethe's eyes hungrily traced the motion."
    y "So..."
    "Yuki started to say something, but was quickly interrupted."
    z "I love you."
    yN "(W-What?!)"
    z "I love you, Yuki. There's just something about you that drives me crazy."
    "Yuki felt shocked, but [his] brain was too fried to make any meaningful sounds."
    y "B-Buh?"
    yN "(Great job sounding smart there...)"
    "Although [hed] expected a snarky remark, Zethe's face held only a smile."
    z "At first, I found you infuriating. I hated everything about you."
    "Yuki's chest tightened. Zethe immediately noticed the shift in [his] demeanor."
    z "B-But quickly, I became unable to take my eyes of you. When you were around, I could not stop looking at you. When you were gone, I was always thinking of you."
    z "I wanted you to be mine. And in turn..."
    "Zethe sucked in a sharp breath."
    z "I wanted to be yours."
    "Zethe tenderly tapped his forehead to Yuki's."
    z "Please...!"
    "His words were so desperate that it pulled at Yuki's heartstrings."

    call .accept

    return

label .accept:
    "Yuki took a deep breath and steadied [himself]."
    y "I feel the same about you, Zethe."
    "Zethe's eyes lit up."
    z "Really?"
    "His face continued such joy it was impossible for Yuki to resist. [He] moved [his] hand over Zethe's and linked their fingers together."
    y "Yes, I meant it. I..."
    "Yuki felt his throat tighten. The words \"I love you\" were too much at the moment."
    "So [he] settled for the strongest words [he] could manage."
    y "I care about you too. A lot."
    "Zethe's eyes softened and become moist."
    z "I can't... I can't believe this... I just..."
    "To save him from his trouble with words, Yuki gave Zethe a quick kiss on the lips."
    #shock expression for z
    z "..."
    z "Today, you have made me the second happiest man on this planet."
    y "The {i}second{/i} happiest?"
    z "Yes, because I made you the happiest one."
    "Zethe flashed his cocky smile, but it twitched with a hint of nervousness. Yuki felt [his] heart melt."
    yN "(Is this what being in love is like...?)"

    return